version: "3.7"
services:
  pie-tunes-domain:
    image: pie-tunes-domain:latest
    container_name: "pie-tunes-domain-prod"
    networks:
      - pie-tunes-network-prod
    ports:
      - "8080:8080"
    restart: always
    volumes:
      -  pie-tunes-users-database:/opt/data
    environment:
      - NEO4J_URL=bolt://pie-tunes-neo4j-prod:7687
      - MINIO_URL=http://pie-tunes-minio-prod:9000

volumes:
  pie-tunes-users-database:
    name: pie-tunes-users-database

networks:
  pie-tunes-network-prod:
    name: pie-tunes-network-prod
    external: true
