services:
  pie-tunes-domain:
    image: pie-tunes-domain:latest
    container_name: "pie-tunes-domain-prod"
    networks:
      - pie-tunes-network-prod
    ports:
      - "8080:8080"
    restart: always
    volumes:
      -  ${DATABASE_DIR:-./data}:/opt/data
    environment:
      - NEO4J_URL=${NEO4J_URL}
      - MINIO_URL=${MINIO_URL}
      - JWT_TOKEN_SECRET_KEY=${JWT_TOKEN_SECRET_KEY}
      - UI_SERVER_URL=${UI_SERVER_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKETS_COVERS=${MINIO_BUCKETS_COVERS}
      - MINIO_BUCKETS_TRACKS=${MINIO_BUCKETS_TRACKS}

networks:
  pie-tunes-network-prod:
    name: pie-tunes-network-prod
