version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j-container_name'
    environment:
      NEO4J_AUTH: neo4j/secret123
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./export/neo4j/data:/data
      - ./export/neo4j/var/lib/neo4j/conf:/var/lib/neo4j/conf
      - ./export/neo4j/var/lib/neo4j/import:/var/lib/neo4j/import
      - ./export/neo4j/plugins:/plugins